title: "Rabeea Fatima"
description: "Electrical & Computer Engineer | ASIC & FPGA Enthusiast"
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme

author:
  name: "Rabeea Fatima"
  email: "rabeeafatima@gmail.com"
  github: "https://github.com/RabeeaFatima"
  linkedin: "https://www.linkedin.com/in/rabeea01/"
  location: "Austin, Texas, United States"

# Navigation Menu
nav:
  - title: "About"
    url: "#about"
  - title: "Projects"
    url: "#projects"
  - title: "Publications"
    url: "#publications"
  - title: "Skills"
    url: "#skills"
  - title: "Contact"
    url: "#contact"
